In [1]:
import numpy as np

## Dot and Matrix Products of two Arrays

In [14]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]]);
arr2 = np.array([[3,2,1],[6,5,4],[9,8,7]]); 
arr3 = np.array([[5,6],[8,9]])

#DOT PRODUCT
DotProd = np.dot(arr1,arr2)
CrossProd = np.cross(arr1,arr2)
print("Dot Product of arr1 & arr2:\n",DotProd)
print("\nCross Product of arr1 & arr2:\n",CrossProd)

#EIGEN VALUES
print("\n\nEigen Values of arr2 :", np.linalg.eigvals(arr2))

# SOLVE
# 3 * x0 + x1 = 9, x0 + 2 * x1 = 8
# AX = B
A = np.array([[3,1],
            [1,2]]);
B = np.array([9,8]);
print("\n\nSolution of the linear equation 3*x\u2080 + x\u2081 = 9 & x\u2080 + 2*x\u2081 = 8 is ", np.linalg.solve(A,B).astype(np.int64))

#MULTIPLICATIVE INVERSE
print("\n\nMultiplicative Inverse of arr3:\n", np.linalg.inv(arr3)) 

Dot Product of arr1 & arr2:
 [[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]

Cross Product of arr1 & arr2:
 [[ -4   8  -4]
 [-10  20 -10]
 [-16  32 -16]]


Eigen Values of arr2 : [1.36846584e+01 1.31534156e+00 1.06234298e-17]


Solution of the linear equation 3*x₀ + x₁ = 9 & x₀ + 2*x₁ = 8 is  [2 3]


Multiplicative Inverse of arr3:
 [[-3.          2.        ]
 [ 2.66666667 -1.66666667]]


In [7]:
#DOT PRODUCT
DotProd = np.dot(arr1,arr2)
CrossProd = np.cross(arr1,arr2)
print("Dot Product of arr1 & arr2:\n",DotProd)
print("Cross Product of arr1 & arr2:\n",CrossProd)


Rank of Matrix arr1 is: 2


Determinant of Matrix A is: 5
