In [7]:
import numpy as np

## Create a Multi dimensional array and find its Shape and Dimension

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(arr)
print("Shape of the Matrix", arr.shape)
print("Dimension of the Matrix",arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the Matrix (3, 3)
Dimension of the Matrix 2


## Create a Matrix full of Zeros and ones

In [10]:
#Matrix of Zeros
arr0 = np.zeros((2,3))
arr1 = np.ones((3,2))
print("Matrix of Zeros\n",arr0)
print("Matrix of Ones\n",arr1)

Matrix of Zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
Matrix of Ones
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


## Reshape and Flatten the data in the matrix

In [11]:
#Reshaping to 3,2
arr1 = arr1.reshape((1,3,2))
arr0 = arr0.flatten()
print("Array after reshaping\n",arr1)
print("Array after flattening\n",arr0)

Array after reshaping
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]]
Array after flattening
 [0. 0. 0. 0. 0. 0.]


## Apply Indexing and Slicing

In [12]:
#indexing
print("Element at index (2,1) in arr:",arr[2,1])
print("Elements of 2nd Row: ",arr[1,0:3])

Element at index (2,1) in arr: 8
Elements of 2nd Row:  [4 5 6]


## Append Data vertically and Horizontally

In [13]:
print("Horrizontal Append",np.append(arr0,arr1))
print("Vertical Append\n", np.append(arr1.reshape((2,3)),arr0.reshape((2,3)),axis=0))

Horrizontal Append [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
Vertical Append
 [[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Using Statistical Function find Mean, Median, Standard Deviation, Max and Min

In [14]:
print("Min element of arr is: ", np.min(arr))
print("Max element of arr is: ", np.max(arr))
print("Mean of arr is: ", np.mean(arr))
print("Median of arr is: ", np.median(arr))
print(f'Standard Deviation of arr1 is: {np.std(arr):.2f}')

Min element of arr is:  1
Max element of arr is:  9
Mean of arr is:  5.0
Median of arr is:  5.0
Standard Deviation of arr1 is: 2.58
